version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql


  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # command: bundle exec thin start --ssl -p 3000
    volumes:
      - .:/myapp
    ports:
      # - "3000:3000"
      - "3000:3000"
    depends_on:
      - db